services:
  quotes:
    container_name: "quotes"
    image: ghcr.io/cegredev/thats-a-quote:latest
    volumes:
      - "path/to/storage:/app/data"
    ports:
      - "3000:3000"
    environment:
      - BETTER_AUTH_URL=http://localhost:3000 # Your URL
      - BETTER_AUTH_SECRET=NOT-A-REAL-SECRET # Your secret
